version: 0.1

environment_variables:
  plaintext:
    key: "value"

            
phases:
  install:
    commands:
      - echo "install phase"
  pre_build:
    commands:
      - echo "pre_build phase"
  build:
    commands:
      - docker build -t thing:dockerthing .
      - docker images
  post_build:
    commands:
      - echo "post_build phase"
