version: 0.1

environment_variables:
  plaintext:

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get -y install docker.io
      - ln -sf /usr/bin/docker.io /usr/local/bin/docker
      - update-rc.d docker defaults
      - service docker start
  pre_build:
    commands:

  build:
    commands:
      - docker build -t thing:dockerthing .

  post_build:
    commands:

artifacts:
  files:

  discard-paths: yes