# sudo apt-get install curl linux-image-extra-$(uname -r) linux-image-extra-virtual && sudo apt-get install -y lsb-release apt-transport-https ca-certificates && curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add - && sudo add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main" && sudo apt-get update && sudo apt-get -y install docker-engine && sudo docker build -t thing:dockerthing .

version: 0.1

environment_variables:
  plaintext:
#     key: "value"
#     key: "value"
            
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get -y install docker.io
      - ln -sf /usr/bin/docker.io /usr/local/bin/docker
      - update-rc.d docker defaults
      - service docker start
  pre_build:
    commands:
#       - command
#       - command
  build:
    commands:
      - docker build -t thing:dockerthing .
    #   - command
  post_build:
    commands:
#       - command
#       - command
artifacts:
  files:
#     - location
#     - location
  discard-paths: yes