version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-west-2"
    GIT_IMAGE_REPO_NAME: "dockerthing"
    AWS_IMAGE_REPO_NAME: "dnbi/scoring"
    IMAGE_TAG: "dockerthing100"
    AWS_ACCOUNT_ID: "236573294224"
          
phases:
  install:
    commands:
      - echo "install phase"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      # - docker build -t thing:dockerthing .
      - docker build -t $GIT_IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $GIT_IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_REPO_NAME:$IMAGE_TAG
      - docker images
  post_build:
    commands:
      - echo "post_build phase"
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_REPO_NAME:$IMAGE_TAG
     
