# sudo apt-get install curl linux-image-extra-$(uname -r) linux-image-extra-virtual && sudo apt-get install -y lsb-release apt-transport-https ca-certificates && curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add - && sudo add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main" && sudo apt-get update && sudo apt-get -y install docker-engine && sudo docker build -t thing:dockerthing .

version: 0.1

environment_variables:
  plaintext:
    key: "value"

            
phases:
  install:
    commands:
      - echo "install phase"
  pre_build:
    commands:
      - echo "pre_build phase"
  build:
    commands:
      - docker build -t thing:dockerthing .
      - docker images
  post_build:
    commands:
      - echo "post_build phase"

  discard-paths: yes